services:

  redis:
    image: 'redis:7.2.5-alpine'
    volumes:
      - redis-data:/data
    ports:
      - '63791:6379'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 2s
      retries: 5

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - "54321:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: ["bash", "docker/app/start.sh"]
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy

  celery:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: ["bash", "docker/app/start.sh"]
    environment:
      - REDIS_URL=${REDIS_URL}
      - CELERY_MODE=1
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    depends_on:
      - redis
      - app

volumes:
  pg-data:
  redis-data: