"""remov_single_field_unique_indexes

Revision ID: 0631bded7d36
Revises: 7d6fc4b5ffa9
Create Date: 2024-05-20 22:47:34.951668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0631bded7d36'
down_revision: Union[str, None] = '7d6fc4b5ffa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channels_channel_url_key', 'channels', type_='unique')
    op.drop_constraint('channels_title_key', 'channels', type_='unique')
    op.drop_constraint('videos_video_url_key', 'videos', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('videos_video_url_key', 'videos', ['video_url'])
    op.create_unique_constraint('channels_title_key', 'channels', ['title'])
    op.create_unique_constraint('channels_channel_url_key', 'channels', ['channel_url'])
    # ### end Alembic commands ###
