"""update_channel_model

Revision ID: 611f33673724
Revises: 51a9971ea593
Create Date: 2024-05-20 09:34:13.745439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611f33673724'
down_revision: Union[str, None] = '51a9971ea593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('title', sa.String(), nullable=False))
    op.drop_constraint('channels_name_key', 'channels', type_='unique')
    op.create_unique_constraint(None, 'channels', ['title'])
    op.drop_column('channels', 'description')
    op.drop_column('channels', 'followers_count')
    op.drop_column('channels', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('channels', sa.Column('followers_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('channels', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'channels', type_='unique')
    op.create_unique_constraint('channels_name_key', 'channels', ['name'])
    op.drop_column('channels', 'title')
    # ### end Alembic commands ###
