"""add_unique_indexes

Revision ID: 7d6fc4b5ffa9
Revises: 611f33673724
Create Date: 2024-05-20 22:16:35.888380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6fc4b5ffa9'
down_revision: Union[str, None] = '611f33673724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_channel', 'channels', ['user_id', 'channel_url'])
    op.create_unique_constraint('uix_channel_video', 'videos', ['channel_id', 'video_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_channel_video', 'videos', type_='unique')
    op.drop_constraint('uix_user_channel', 'channels', type_='unique')
    # ### end Alembic commands ###
